const fs = require('fs');
const path = require('path');

const SRC_DIR = path.join(__dirname, 'Assets', 'JS');
const OUTPUT_FILE = path.join(SRC_DIR, 'ZembiS_Calendar.js');

// LOAD ORDER MATTERS: EACH FILE DEPENDS ON THE CLASSES DEFINED BEFORE IT
const FILES = [
    'classes/EventHandler.js',
    'classes/DOMManager.js',
    'classes/DateManager.js',
    'classes/ConfigManager.js',
    'classes/ValidatorHandle.js',
    'classes/Calendar_Controller.js',
];

const banner = `/*
 * ZembiS_Calendar - bundled build
 * Generated by build.js - do not edit this file directly.
 * Edit the source files in Assets/JS/classes/,
 * then run \`npm run build\` (or \`node build.js\`) to regenerate this file.
 */
`;

const contents = FILES.map(file => fs.readFileSync(path.join(SRC_DIR, file), 'utf8'));

const bundle = `${banner}(function () {\n${contents.join('\n')}\n})();\n`;

fs.writeFileSync(OUTPUT_FILE, bundle);
console.log(`Built ${path.relative(__dirname, OUTPUT_FILE)} from ${FILES.length} source files.`);
